#!/bin/sh

# asset compactor wrapper

if [ -z $1 ]; then
  echo "Asset directory not provided"
  exit 1
fi

if [ ! -d "$1" ]; then
  echo "Not a directory: $1"
  exit 1
fi

if [ -z $2 ]; then
  echo "Work directory not provided"
  exit 1
fi

if [ ! -d "$2" ]; then
  echo "Not a directory: $2"
  exit 1
fi

if [ -z $3 ]; then
  echo "S3 bucket/path not provided"
  exit 1
fi

DIR="$(basename ${1})"

# make sure the directory exist first
sudo mkdir -p /var/log/assetcompactor

# run in docker, append to all and specific log files, silence output for cron reasons
sudo docker run                                                                \
  --detach=false                                                               \
  --rm                                                                         \
  --volume="${2}":/datadir/                                                    \
  --volume="${1}":"/datadir/${DIR}"                                            \
  --volume=/etc/aws/assetcompactor:/root/.aws                                  \
  fulcrum/assetcompactor "/datadir/${DIR}" "${3}"                              |
sudo tee -a /var/log/assetcompactor/all.log /var/log/assetcompactor/${DIR}.log > /dev/null
