#!/bin/sh

# asset compactor wrapper

if [ -z $1 ]; then
  echo "Directory not provided"
  exit 1
fi

if [ -z $2 ]; then
  echo "S3 bucket/path not provided"
  exit 1
fi

if [ ! -d $1 ]; then
  echo "Not a directory: $1"
  exit 1
fi

sudo docker run                                                        \
  --detach=false                                                       \
  --rm                                                                 \
  --volume="${1}":"/assetcompactordata/$(basename ${1})"               \
  --volume=/etc/aws/assetcompactor:/root/.aws                          \
  fulcrum/assetcompactor "/assetcompactordata/$(basename ${1})" "${2}"
